# Generated by Django 3.2.8 on 2022-06-23 17:10

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
