# Generated by Django 3.2.8 on 2022-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': [('contract_assign', 'Может назначить пользователя на выполнение заявки'), ('contract_browse', 'Может просматривать заявки'), ('contract_create', 'Может создавать заявки'), ('contract_edit', 'Может редактировать заявки'), ('contract_comment', 'Может добавлять комментарий к заявке'), ('contract_close', 'Может закрывать заявку'), ('contract_time', 'Может отложить заявку'), ('contract_take', 'Может брать заявку')]},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tsv',
        ),
        migrations.AlterField(
            model_name='contract',
            name='conditions_first',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Индивидуальные'), (2, 'Акционные (0*3)'), (3, '10 дней - за 500'), (4, 'Акционные (0*0)')], default=2, null=True, verbose_name='Условия интернет'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='conditions_two',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Индивидуальные'), (2, 'Акционные (0*3)'), (3, '10 дней - за 500'), (4, 'Акционные (0*0)')], default=4, null=True, verbose_name='Условия телевиденье'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment_first',
            field=models.SmallIntegerField(blank=True, choices=[(0, '841n - 555'), (1, 'ArcherC24 - 800'), (2, 'ArcherC54 - 900'), (3, 'ArcherC5 - 1399'), (4, 'ArcherAx10 - 1599'), (5, 'InextTV5 - 850'), (6, 'Не требуется')], default=6, null=True, verbose_name='Оборудование интернет'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='equipment_two',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Не требуется'), (1, 'InextTV5 - 850')], default=0, null=True, verbose_name='Оборудование телевиденье'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='exodus_in',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Отказ'), (1, 'Оформленно'), (2, 'Консультация')], default=1, null=True, verbose_name='Исход интернет'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='exodus_tv',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Отказ'), (1, 'Оформленно'), (2, 'Консультация')], default=1, null=True, verbose_name='Исход телевиденье'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Отсутствует'), (1, 'В работе'), (2, 'Нет ответа'), (3, 'Подумает'), (4, 'Неверная'), (5, 'Выполнено')], default=0, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_first',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'HOME в Многокварт.'), (2, 'GPON в Многокварт.'), (3, 'GPON в Частный'), (4, 'Radio в Частный'), (5, 'Индивидуальное')], null=True, verbose_name='Тип подключения интернет'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_two',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Не выбрано'), (1, 'IPTV'), (2, 'Аналоговое Телевиденье'), (3, 'IPTV в Тест. Режиме')], null=True, verbose_name='Тип подключения телевиденье'),
        ),
    ]
