# Generated by Django 3.2.8 on 2022-09-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'permissions': [('contract_assign', 'Может назначить пользователя на выполнение заявки'), ('contract_browse', 'Может просматривать список заявок'), ('contract_create', 'Может создавать заявки'), ('contract_edit', 'Может редактировать заявки'), ('contract_close', 'Может закрывать заявку'), ('contract_time', 'Может отложить заявку'), ('contract_take', 'Может брать заявку в обработку'), ('contract_browse_statistics', "Может просматривать 'Статистику'")]},
        ),
    ]
