# Generated by Django 3.2.8 on 2022-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type_first',
            field=models.SmallIntegerField(choices=[(0, 'Не выбрано'), (1, 'HOME в Многокварт.'), (2, 'GPON в Многокварт.'), (3, 'GPON в Частный'), (4, 'Radio в Частный'), (5, 'Индивидуальное')], default=0, verbose_name='Тип подключения интернет'),
        ),
    ]
