# Generated by Django 3.2.8 on 2022-09-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_contract_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='id_telegram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frontuser',
            name='login_telegram',
            field=models.TextField(default='Неизвестно'),
        ),
    ]
