# Generated by Django 3.2.8 on 2022-09-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220907_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuser',
            name='workmail',
            field=models.TextField(blank=True),
        ),
    ]
