# Generated by Django 3.2.8 on 2022-08-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220818_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='priority_service',
            field=models.CharField(blank=True, choices=[(1, 'Интернет'), (2, 'Телевиденье')], default='SERVICE_A', max_length=15, verbose_name='Приоритетная Услуга'),
        ),
    ]
