# Generated by Django 3.2.8 on 2022-08-19 05:37

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_contract_priority_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tsv',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
